# Generated by Django 2.0.7 on 2018-07-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_pizza_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
    ]
