# Generated by Django 2.0.7 on 2018-07-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='name',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
