# Generated by Django 2.0.7 on 2018-08-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_menu_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pizza',
        ),
    ]
