# Generated by Django 2.0.7 on 2018-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_menu_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='size',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
