# Generated by Django 2.0.7 on 2018-08-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_options_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='size',
        ),
    ]
