# Generated by Django 2.0.7 on 2018-08-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_options_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, related_name='subToppings', to='orders.Sub'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='pizzas',
            field=models.ManyToManyField(blank=True, null=True, related_name='pizzaToppings', to='orders.Pizza'),
        ),
    ]
