# Generated by Django 2.0.7 on 2018-08-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180802_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='pizzaToppings', to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subToppings', to='orders.Sub'),
        ),
    ]
