# Generated by Django 2.0.7 on 2018-08-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180802_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='dish',
            field=models.CharField(default='', max_length=64),
        ),
    ]
